# Generated by Django 6.0.1 on 2026-02-01 22:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(db_index=True, max_length=100, verbose_name='Name (English)')),
                ('name_ar', models.CharField(db_index=True, max_length=100, verbose_name='Name (Arabic)')),
                ('slug', models.SlugField(help_text='Unique URL identifier', max_length=150, unique=True, verbose_name='URL Slug')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (Arabic)')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class (e.g., fas fa-store)', max_length=50, verbose_name='Icon Class')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Category Image')),
                ('order', models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Display Order')),
                ('meta_keywords_en', models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords (English)')),
                ('meta_keywords_ar', models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords (Arabic)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name_en'],
                'indexes': [models.Index(fields=['slug'], name='categories__slug_9b1a28_idx'), models.Index(fields=['is_active', 'order'], name='categories__is_acti_350a72_idx'), models.Index(fields=['parent', 'is_active'], name='categories__parent__85acd9_idx')],
            },
        ),
    ]
