# Generated by Django 5.2.17 on 2026-08-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="business_type",
            field=models.CharField(
                choices=[
                    ("shop", "محل تجاري"),
                    ("craft", "حرفة أو مهنة"),
                    ("public", "خدمة عامة"),
                ],
                db_index=True,
                default="shop",
                help_text="الدليل الذي يظهر فيه هذا القسم",
                max_length=20,
                verbose_name="نوع الدليل",
            ),
        ),
    ]
