# Generated by Django 6.0.1

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_infer_category_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={
                'ordering': ['order', 'name_ar'],
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
