# Generated by Django 5.2.17 on 2026-08-05 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('directory', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='معرّف ثابت لا يتغير، مثل operations_manager', unique=True, verbose_name='المعرّف')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('permissions', models.JSONField(default=list, help_text='قائمة أكواد الصلاحيات من PERMISSION_REGISTRY', verbose_name='الصلاحيات')),
                ('is_protected', models.BooleanField(default=False, help_text='الأدوار المحمية لا يمكن حذفها أو تجريدها من صلاحياتها', verbose_name='محمي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
            ],
            options={
                'verbose_name': 'دور إداري',
                'verbose_name_plural': 'الأدوار الإدارية',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, help_text='نسخة نصية تبقى بعد حذف الحساب', max_length=150, verbose_name='اسم المنفّذ')),
                ('actor_role', models.CharField(blank=True, max_length=100, verbose_name='دور المنفّذ')),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('verify', 'توثيق'), ('unverify', 'إلغاء توثيق'), ('feature', 'تمييز'), ('unfeature', 'إلغاء تمييز'), ('approve', 'اعتماد'), ('reject', 'رفض'), ('suspend', 'تعليق'), ('activate', 'تفعيل'), ('role_change', 'تغيير دور'), ('notify', 'إرسال إشعار'), ('login', 'دخول للوحة'), ('bulk', 'عملية جماعية')], max_length=20, verbose_name='العملية')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرّف الهدف')),
                ('target_label', models.CharField(blank=True, max_length=255, verbose_name='اسم الهدف')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='{"field": {"from": ..., "to": ...}}', verbose_name='التغييرات')),
                ('reason', models.TextField(blank=True, verbose_name='السبب')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='المتصفح/الجهاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='التوقيت')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='المنفّذ')),
                ('target_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='نوع الهدف')),
            ],
            options={
                'verbose_name': 'سجل عملية',
                'verbose_name_plural': 'سجل العمليات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='administrat_created_02e1c0_idx'), models.Index(fields=['actor', '-created_at'], name='administrat_actor_i_7aa687_idx'), models.Index(fields=['target_type', 'target_id'], name='administrat_target__0d7d77_idx'), models.Index(fields=['action', '-created_at'], name='administrat_action_0f7900_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='المسمى الوظيفي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('last_admin_login', models.DateTimeField(blank=True, null=True, verbose_name='آخر دخول للوحة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members_created', to=settings.AUTH_USER_MODEL, verbose_name='أضافه')),
                ('governorates', models.ManyToManyField(blank=True, help_text='اتركه فارغًا لمنح صلاحية على كل المحافظات', related_name='scoped_staff', to='directory.governorate', verbose_name='نطاق المحافظات')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='administration.role', verbose_name='الدور')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'موظف إدارة',
                'verbose_name_plural': 'موظفو الإدارة',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='administrat_is_acti_7b5eb2_idx')],
            },
        ),
    ]
