# Generated by Django 4.2.28 on 2026-03-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name_ar",
                    models.CharField(default="دليل أي خدمة", max_length=100),
                ),
                (
                    "site_name_en",
                    models.CharField(default="Daliil Ay Khidma", max_length=100),
                ),
                ("site_description_ar", models.TextField(blank=True)),
                ("site_description_en", models.TextField(blank=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="site/")),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="site/"),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("facebook", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("twitter", models.URLField(blank=True)),
                ("whatsapp", models.CharField(blank=True, max_length=20)),
                ("youtube", models.URLField(blank=True)),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("allow_registration", models.BooleanField(default=True)),
                ("results_per_page", models.PositiveIntegerField(default=12)),
                ("allow_reviews", models.BooleanField(default=True)),
                ("require_review_approval", models.BooleanField(default=True)),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.CharField(blank=True, max_length=255)),
                ("google_analytics_id", models.CharField(blank=True, max_length=50)),
                ("google_maps_key", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "إعدادات الموقع",
            },
        ),
    ]
