# Generated by Django 4.2.30 on 2026-07-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='android_latest_version',
            field=models.CharField(default='1.0.0', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='android_min_version',
            field=models.CharField(default='1.0.0', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='android_store_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='force_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ios_latest_version',
            field=models.CharField(default='1.0.0', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ios_min_version',
            field=models.CharField(default='1.0.0', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ios_store_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_url',
            field=models.URLField(blank=True),
        ),
    ]
