# Generated by Django 6.0.1 on 2026-01-29 17:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(db_index=True, max_length=100)),
                ('name_ar', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['governorate__order', 'order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(db_index=True, help_text='Example: Restaurants, Medical, Shopping', max_length=100, verbose_name='Category Name (English)')),
                ('name_ar', models.CharField(db_index=True, help_text='مثال: مطاعم ومقاهي، طبية، تسوق', max_length=100, verbose_name='اسم الفئة')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL Slug')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف بالعربية')),
                ('icon', models.CharField(blank=True, default='fas fa-store', help_text='Example: fas fa-utensils, fas fa-hospital', max_length=50, verbose_name='Font Awesome Icon')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/%Y/%m/', verbose_name='Category Image')),
                ('order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('meta_keywords_en', models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255, verbose_name='Meta Keywords (English)')),
                ('meta_keywords_ar', models.CharField(blank=True, help_text='كلمات مفتاحية للسيو', max_length=255, verbose_name='الكلمات المفتاحية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('parent', models.ForeignKey(blank=True, help_text='Leave empty for main category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', related_query_name='child', to='directory.category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['parent__order', 'order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(db_index=True, max_length=100)),
                ('name_ar', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='directory.city')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['city__order', 'order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(choices=[('shop', 'محل تجاري / Commercial Shop'), ('craft', 'حرفة أو خدمة حرفية / Craft or Trade Service'), ('public', 'خدمة عامة / Public Service')], db_index=True, default='shop', help_text='اختر نوع المحل: تجاري، حرفي، أو خدمة عامة', max_length=10, verbose_name='نوع المحل / Business Type')),
                ('name_en', models.CharField(db_index=True, help_text='Example: Golden Restaurant, City Pharmacy, Ahmed the Plumber', max_length=200, verbose_name='Business Name (English)')),
                ('name_ar', models.CharField(db_index=True, help_text='مثال: مطعم الذهبي، صيدلية المدينة، أحمد السباك', max_length=200, verbose_name='اسم المحل')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='URL Slug')),
                ('logo', models.ImageField(blank=True, help_text='Recommended: 500x500 px square image', null=True, upload_to='businesses/logos/%Y/%m/', verbose_name='Logo')),
                ('cover_image', models.ImageField(blank=True, help_text='Wide banner image (Recommended: 1200x400 px)', null=True, upload_to='businesses/covers/%Y/%m/', verbose_name='Cover Image')),
                ('phone', models.CharField(help_text='Egyptian mobile number (e.g., 01234567890)', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Egyptian phone number (e.g., 01234567890)', regex='^01[0-2,5]{1}[0-9]{8}$')], verbose_name='Phone Number')),
                ('whatsapp', models.CharField(blank=True, help_text='WhatsApp number (optional)', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Egyptian phone number (e.g., 01234567890)', regex='^01[0-2,5]{1}[0-9]{8}$')], verbose_name='WhatsApp Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('website', models.URLField(blank=True, help_text='Business website (optional)', verbose_name='Website URL')),
                ('facebook', models.URLField(blank=True, help_text='Facebook page URL (optional)', verbose_name='Facebook Page')),
                ('instagram', models.URLField(blank=True, help_text='Instagram profile URL (optional)', verbose_name='Instagram Account')),
                ('twitter', models.URLField(blank=True, help_text='Twitter/X profile URL (optional)', verbose_name='Twitter Account')),
                ('tiktok', models.URLField(blank=True, help_text='TikTok profile URL (optional)', verbose_name='TikTok Account')),
                ('address_en', models.TextField(help_text='Detailed address in English', verbose_name='Address (English)')),
                ('address_ar', models.TextField(help_text='العنوان التفصيلي بالعربية', verbose_name='العنوان')),
                ('location_url', models.URLField(blank=True, help_text='Google Maps location link (optional)', verbose_name='Google Maps URL')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Auto-determined from map', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Auto-determined from map', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude')),
                ('description_en', models.TextField(help_text='Detailed description about the business and services', verbose_name='Description (English)')),
                ('description_ar', models.TextField(help_text='وصف تفصيلي عن المحل والخدمات', verbose_name='الوصف')),
                ('working_hours_en', models.TextField(blank=True, help_text='Example: Sat-Thu: 9 AM - 10 PM | Fri: 2 PM - 10 PM | For public services: 24/7 or specific hours', verbose_name='Working Hours (English)')),
                ('working_hours_ar', models.TextField(blank=True, help_text='مثال: السبت-الخميس: 9 ص-10 م | الجمعة: 2 م-10 م | للخدمات العامة: 24 ساعة أو ساعات محددة', verbose_name='ساعات العمل')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, help_text='Total number of page views', verbose_name='View Count')),
                ('click_count', models.PositiveIntegerField(default=0, editable=False, help_text='Total clicks on contact buttons', verbose_name='Click Count')),
                ('is_active', models.BooleanField(default=False, help_text='Enable/disable business visibility on the site', verbose_name='Active')),
                ('is_verified', models.BooleanField(default=False, help_text='Business has been verified by admin', verbose_name='Verified')),
                ('is_featured', models.BooleanField(default=False, help_text='Display in featured businesses section', verbose_name='Featured')),
                ('is_promoted', models.BooleanField(default=False, help_text='Promoted businesses (paid promotion)', verbose_name='Promoted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Date when business was verified', null=True, verbose_name='Verified At')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', related_query_name='business', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='businesses', related_query_name='business', to='directory.category', verbose_name='Category')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='businesses', related_query_name='business', to='directory.district', verbose_name='District')),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Added At')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', related_query_name='favorited_by_user', to='directory.business', verbose_name='Business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', related_query_name='favorite', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(db_index=True, help_text='Example: Ismailia, Cairo, Alexandria', max_length=100, verbose_name='Name (English)')),
                ('name_ar', models.CharField(db_index=True, help_text='مثال: الإسماعيلية، القاهرة، الإسكندرية', max_length=100, verbose_name='الاسم بالعربية')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, default='fas fa-city', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='governorates/%Y/%m/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Governorate',
                'verbose_name_plural': 'Governorates',
                'ordering': ['order', 'name_en'],
                'indexes': [models.Index(fields=['slug'], name='directory_g_slug_a530e1_idx'), models.Index(fields=['is_active', 'order'], name='directory_g_is_acti_c59c66_idx')],
                'constraints': [models.UniqueConstraint(fields=('name_en',), name='unique_governorate_name_en'), models.UniqueConstraint(fields=('name_ar',), name='unique_governorate_name_ar')],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='directory.governorate'),
        ),
        migrations.CreateModel(
            name='BusinessImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='businesses/gallery/%Y/%m/', verbose_name='Image')),
                ('caption_en', models.CharField(blank=True, max_length=200, verbose_name='Caption (English)')),
                ('caption_ar', models.CharField(blank=True, max_length=200, verbose_name='الوصف')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', related_query_name='image', to='directory.business', verbose_name='Business')),
            ],
            options={
                'verbose_name': 'Business Image',
                'verbose_name_plural': 'Business Images',
                'ordering': ['order', '-uploaded_at'],
                'indexes': [models.Index(fields=['business', 'is_active'], name='directory_b_busines_02693a_idx'), models.Index(fields=['order'], name='directory_b_order_a8b261_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='directory_c_slug_2e5f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active'], name='directory_c_parent__6535a3_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'order'], name='directory_c_is_acti_947875_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['slug'], name='directory_d_slug_9838a8_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['city', 'is_active'], name='directory_d_city_id_7c971a_idx'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('city', 'name_en'), name='unique_district_name_en_per_city'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('city', 'name_ar'), name='unique_district_name_ar_per_city'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['slug'], name='directory_b_slug_c6091d_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['business_type'], name='directory_b_busines_5019cb_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['business_type', 'is_active'], name='directory_b_busines_ada034_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_active', 'is_verified'], name='directory_b_is_acti_7561dd_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['category', 'is_active'], name='directory_b_categor_6c6136_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['district', 'is_active'], name='directory_b_distric_79407c_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['-view_count'], name='directory_b_view_co_8b070f_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_featured', '-created_at'], name='directory_b_is_feat_6c0e53_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_promoted', '-created_at'], name='directory_b_is_prom_c5d475_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['owner', 'is_active'], name='directory_b_owner_i_4e66c5_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', '-created_at'], name='directory_f_user_id_672b9c_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['business', '-created_at'], name='directory_f_busines_bccdb6_idx'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'business'), name='unique_user_business_favorite'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['slug'], name='directory_c_slug_e98328_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['governorate', 'is_active'], name='directory_c_governo_a44d9b_idx'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('governorate', 'name_en'), name='unique_city_name_en_per_gov'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('governorate', 'name_ar'), name='unique_city_name_ar_per_gov'),
        ),
    ]
