# Generated by Django 6.0.1 on 2026-02-01 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('directory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], verbose_name='Day of Week')),
                ('opening_time', models.TimeField(verbose_name='Opening Time')),
                ('closing_time', models.TimeField(verbose_name='Closing Time')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Closed on this day')),
            ],
            options={
                'verbose_name': 'Working Hours',
                'verbose_name_plural': 'Working Hours',
                'ordering': ['day'],
            },
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='directory_c_slug_2e5f8c_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='directory_c_parent__6535a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='directory_c_is_acti_947875_idx',
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_set', related_query_name='business', to='categories.category', verbose_name='Category'),
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_user_business_favorite',
        ),
        migrations.AlterField(
            model_name='business',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, help_text='Enable/disable business visibility on the site', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='business',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Display in featured businesses section', verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='business',
            name='is_promoted',
            field=models.BooleanField(db_index=True, default=False, help_text='Promoted businesses (paid promotion)', verbose_name='Promoted'),
        ),
        migrations.AlterField(
            model_name='business',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Business has been verified by admin', verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', related_query_name='favorite', to='directory.business', verbose_name='Business'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'business')},
        ),
        migrations.AddField(
            model_name='businessworkinghours',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours_detailed', related_query_name='working_hour', to='directory.business', verbose_name='Business'),
        ),
        migrations.AlterUniqueTogether(
            name='businessworkinghours',
            unique_together={('business', 'day')},
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
