# Generated by Django 6.0.1 on 2026-02-01 23:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('directory', '0002_businessworkinghours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-is_featured', '-is_promoted', '-created_at'], 'verbose_name': 'Business', 'verbose_name_plural': 'Businesses'},
        ),
        migrations.AddField(
            model_name='business',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Auto-calculated from reviews', max_digits=3, verbose_name='Average Rating'),
        ),
        migrations.AddField(
            model_name='business',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Auto-calculated count of approved reviews', verbose_name='Total Reviews'),
        ),
        migrations.AddField(
            model_name='businessworkinghours',
            name='is_24_hours',
            field=models.BooleanField(default=False, verbose_name='Open 24 Hours'),
        ),
        migrations.AlterField(
            model_name='business',
            name='working_hours_ar',
            field=models.TextField(blank=True, help_text='مثال: السبت-الخميس: 9 ص-10 م | الجمعة: 2 م-10 م', verbose_name='ساعات العمل'),
        ),
        migrations.AlterField(
            model_name='business',
            name='working_hours_en',
            field=models.TextField(blank=True, help_text='Example: Sat-Thu: 9 AM - 10 PM | Fri: 2 PM - 10 PM', verbose_name='Working Hours (English)'),
        ),
        migrations.AlterField(
            model_name='businessworkinghours',
            name='closing_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Closing Time'),
        ),
        migrations.AlterField(
            model_name='businessworkinghours',
            name='day',
            field=models.IntegerField(choices=[(0, 'الأحد / Sunday'), (1, 'الإثنين / Monday'), (2, 'الثلاثاء / Tuesday'), (3, 'الأربعاء / Wednesday'), (4, 'الخميس / Thursday'), (5, 'الجمعة / Friday'), (6, 'السبت / Saturday')], verbose_name='Day of Week'),
        ),
        migrations.AlterField(
            model_name='businessworkinghours',
            name='opening_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Opening Time'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['-average_rating'], name='directory_b_average_9ce1e5_idx'),
        ),
        migrations.AddIndex(
            model_name='businessworkinghours',
            index=models.Index(fields=['business', 'day'], name='directory_b_busines_2ae313_idx'),
        ),
    ]
