# Generated by Django 4.2.28 on 2026-02-13 10:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0003_alter_business_options_business_average_rating_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="city",
            name="unique_city_name_en_per_gov",
        ),
        migrations.RemoveConstraint(
            model_name="city",
            name="unique_city_name_ar_per_gov",
        ),
        migrations.RemoveConstraint(
            model_name="district",
            name="unique_district_name_en_per_city",
        ),
        migrations.RemoveConstraint(
            model_name="district",
            name="unique_district_name_ar_per_city",
        ),
        migrations.RemoveConstraint(
            model_name="governorate",
            name="unique_governorate_name_en",
        ),
        migrations.RemoveConstraint(
            model_name="governorate",
            name="unique_governorate_name_ar",
        ),
        migrations.RenameIndex(
            model_name="city",
            new_name="city_slug_idx",
            old_name="directory_c_slug_e98328_idx",
        ),
        migrations.RenameIndex(
            model_name="city",
            new_name="city_gov_active_idx",
            old_name="directory_c_governo_a44d9b_idx",
        ),
        migrations.RenameIndex(
            model_name="district",
            new_name="district_slug_idx",
            old_name="directory_d_slug_9838a8_idx",
        ),
        migrations.RenameIndex(
            model_name="district",
            new_name="district_city_active_idx",
            old_name="directory_d_city_id_7c971a_idx",
        ),
        migrations.RenameIndex(
            model_name="governorate",
            new_name="gov_slug_idx",
            old_name="directory_g_slug_a530e1_idx",
        ),
        migrations.RenameIndex(
            model_name="governorate",
            new_name="gov_active_order_idx",
            old_name="directory_g_is_acti_c59c66_idx",
        ),
        migrations.AlterField(
            model_name="city",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="city",
            name="description_ar",
            field=models.TextField(blank=True, verbose_name="الوصف (عربي)"),
        ),
        migrations.AlterField(
            model_name="city",
            name="description_en",
            field=models.TextField(blank=True, verbose_name="Description (English)"),
        ),
        migrations.AlterField(
            model_name="city",
            name="governorate",
            field=models.ForeignKey(
                help_text="The governorate this city belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="directory.governorate",
                verbose_name="Governorate",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active Status"),
        ),
        migrations.AlterField(
            model_name="city",
            name="name_ar",
            field=models.CharField(
                db_index=True,
                help_text="اسم المدينة بالعربية",
                max_length=100,
                verbose_name="الاسم (عربي)",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="name_en",
            field=models.CharField(
                db_index=True,
                help_text="City name in English",
                max_length=100,
                verbose_name="Name (English)",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Display Order"),
        ),
        migrations.AlterField(
            model_name="city",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=100, unique=True, verbose_name="URL Slug"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
        ),
        migrations.AlterField(
            model_name="district",
            name="city",
            field=models.ForeignKey(
                help_text="The city this district belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="districts",
                to="directory.city",
                verbose_name="City",
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="district",
            name="description_ar",
            field=models.TextField(blank=True, verbose_name="الوصف (عربي)"),
        ),
        migrations.AlterField(
            model_name="district",
            name="description_en",
            field=models.TextField(blank=True, verbose_name="Description (English)"),
        ),
        migrations.AlterField(
            model_name="district",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active Status"),
        ),
        migrations.AlterField(
            model_name="district",
            name="name_ar",
            field=models.CharField(
                db_index=True,
                help_text="اسم الحي بالعربية",
                max_length=100,
                verbose_name="الاسم (عربي)",
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="name_en",
            field=models.CharField(
                db_index=True,
                help_text="District name in English",
                max_length=100,
                verbose_name="Name (English)",
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Display Order"),
        ),
        migrations.AlterField(
            model_name="district",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=100, unique=True, verbose_name="URL Slug"
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
        ),
        migrations.AlterField(
            model_name="governorate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="governorate",
            name="description_ar",
            field=models.TextField(
                blank=True,
                help_text="وصف مختصر للمحافظة بالعربية",
                verbose_name="الوصف (عربي)",
            ),
        ),
        migrations.AlterField(
            model_name="governorate",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Brief description of the governorate in English",
                verbose_name="Description (English)",
            ),
        ),
        migrations.AlterField(
            model_name="governorate",
            name="icon",
            field=models.CharField(
                blank=True,
                default="fas fa-city",
                help_text="FontAwesome icon class (default: fas fa-city)",
                max_length=50,
                verbose_name="Icon Class",
            ),
        ),
        migrations.AlterField(
            model_name="governorate",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Representative image for the governorate (optional)",
                null=True,
                upload_to="governorates/%Y/%m/",
                verbose_name="Governorate Image",
            ),
        ),
        migrations.AlterField(
            model_name="governorate",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Inactive governorates will be hidden from public view",
                verbose_name="Active Status",
            ),
        ),
        migrations.AlterField(
            model_name="governorate",
            name="name_ar",
            field=models.CharField(
                db_index=True,
                help_text="اسم المحافظة بالعربية (مثال: القاهرة، الإسكندرية، الجيزة)",
                max_length=100,
                verbose_name="الاسم (عربي)",
            ),
        ),
        migrations.AlterField(
            model_name="governorate",
            name="name_en",
            field=models.CharField(
                db_index=True,
                help_text="Governorate name in English (e.g., Cairo, Alexandria, Giza)",
                max_length=100,
                verbose_name="Name (English)",
            ),
        ),
        migrations.AlterField(
            model_name="governorate",
            name="order",
            field=models.IntegerField(
                default=0,
                help_text="Order for displaying in lists (lower numbers appear first)",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Display Order",
            ),
        ),
        migrations.AlterField(
            model_name="governorate",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Auto-generated from English name for SEO-friendly URLs",
                max_length=100,
                unique=True,
                verbose_name="URL Slug",
            ),
        ),
        migrations.AlterField(
            model_name="governorate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
        ),
        migrations.AddConstraint(
            model_name="city",
            constraint=models.UniqueConstraint(
                fields=("governorate", "name_en"),
                name="unique_city_name_en_per_gov",
                violation_error_message="A city with this English name already exists in this governorate.",
            ),
        ),
        migrations.AddConstraint(
            model_name="city",
            constraint=models.UniqueConstraint(
                fields=("governorate", "name_ar"),
                name="unique_city_name_ar_per_gov",
                violation_error_message="مدينة بهذا الاسم موجودة بالفعل في هذه المحافظة.",
            ),
        ),
        migrations.AddConstraint(
            model_name="district",
            constraint=models.UniqueConstraint(
                fields=("city", "name_en"),
                name="unique_district_name_en_per_city",
                violation_error_message="A district with this English name already exists in this city.",
            ),
        ),
        migrations.AddConstraint(
            model_name="district",
            constraint=models.UniqueConstraint(
                fields=("city", "name_ar"),
                name="unique_district_name_ar_per_city",
                violation_error_message="حي بهذا الاسم موجود بالفعل في هذه المدينة.",
            ),
        ),
        migrations.AddConstraint(
            model_name="governorate",
            constraint=models.UniqueConstraint(
                fields=("name_en",),
                name="unique_governorate_name_en",
                violation_error_message="A governorate with this English name already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="governorate",
            constraint=models.UniqueConstraint(
                fields=("name_ar",),
                name="unique_governorate_name_ar",
                violation_error_message="محافظة بهذا الاسم العربي موجودة بالفعل.",
            ),
        ),
    ]
