# Generated by Django 5.2.17 on 2026-08-06 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0004_remove_city_unique_city_name_en_per_gov_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="source",
            field=models.CharField(
                choices=[
                    ("owner", "صاحب النشاط"),
                    ("staff", "موظف الإدارة"),
                    ("imported", "مستورَد"),
                ],
                db_index=True,
                default="owner",
                max_length=20,
                verbose_name="المصدر",
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_businesses",
                related_query_name="verified_business",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تحقق منه",
            ),
        ),
    ]
