# Generated by Django 6.0.1 on 2026-01-29 17:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Free / مجاني'), ('basic', 'Basic / أساسي'), ('premium', 'Premium / مميز'), ('vip', 'VIP / نخبة')], max_length=20, unique=True, verbose_name='Plan Name')),
                ('display_name_en', models.CharField(max_length=50, verbose_name='Display Name (English)')),
                ('display_name_ar', models.CharField(max_length=50, verbose_name='الاسم المعروض')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monthly Price (EGP)')),
                ('price_quarterly', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quarterly Price (EGP)')),
                ('price_semi_annual', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Semi-Annual Price (EGP)')),
                ('price_annual', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Annual Price (EGP)')),
                ('max_products', models.PositiveIntegerField(default=0, help_text='0 = Unlimited', verbose_name='Max Products')),
                ('max_images_per_product', models.PositiveIntegerField(default=1, help_text='Number of images allowed per product', verbose_name='Max Images per Product')),
                ('max_business_images', models.PositiveIntegerField(default=3, help_text='Number of gallery images for business', verbose_name='Max Business Gallery Images')),
                ('can_upload_images', models.BooleanField(default=False, verbose_name='Can Upload Images')),
                ('can_show_prices', models.BooleanField(default=False, verbose_name='Can Show Prices')),
                ('has_delivery_options', models.BooleanField(default=False, verbose_name='Delivery Options Available')),
                ('has_analytics', models.BooleanField(default=False, verbose_name='Analytics Dashboard')),
                ('featured_in_search', models.BooleanField(default=False, help_text='Higher priority in search results', verbose_name='Featured in Search Results')),
                ('can_create_deals', models.BooleanField(default=False, verbose_name='Can Create Deals/Offers')),
                ('has_social_media_links', models.BooleanField(default=True, verbose_name='Social Media Links')),
                ('has_verified_badge', models.BooleanField(default=False, verbose_name='Verified Badge')),
                ('color', models.CharField(default='#6c757d', help_text='Hex color code (e.g., #007bff)', max_length=7, verbose_name='Badge Color')),
                ('icon', models.CharField(default='fas fa-tag', max_length=50, verbose_name='Font Awesome Icon')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_popular', models.BooleanField(default=False, help_text='Display "Most Popular" badge', verbose_name='Popular Plan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('status', models.CharField(choices=[('active', 'Active / نشط'), ('expired', 'Expired / منتهي'), ('cancelled', 'Cancelled / ملغي'), ('pending', 'Pending Payment / بانتظار الدفع')], db_index=True, default='pending', max_length=10, verbose_name='Status')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='Auto Renew')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount Paid (EGP)')),
                ('payment_method', models.CharField(blank=True, help_text='e.g., Credit Card, PayPal, Bank Transfer', max_length=50, verbose_name='Payment Method')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Transaction ID')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (not visible to user)', verbose_name='Admin Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='directory.business', verbose_name='Business')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', related_query_name='subscription', to='subscriptions.subscriptionplan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'status'], name='subscriptio_busines_ad9254_idx'), models.Index(fields=['status', 'end_date'], name='subscriptio_status_5ff966_idx'), models.Index(fields=['-created_at'], name='subscriptio_created_cd574f_idx')],
            },
        ),
    ]
