# Generated by Django 5.x

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_change_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly / شهري'), ('quarterly', 'Quarterly / ربع سنوي'), ('semi_annual', 'Semi-Annual / نصف سنوي'), ('annual', 'Annual / سنوي')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft / مسودة'), ('plan_selected', 'Plan Selected / تم اختيار الخطة'), ('business_created', 'Business Created / تم إنشاء النشاط'), ('payment_pending', 'Payment Pending / بانتظار الدفع'), ('admin_review', 'Admin Review / بانتظار مراجعة الإدارة'), ('subscription_active', 'Subscription Active / الاشتراك مفعل'), ('completed', 'Completed / مكتمل')], db_index=True, default='draft', max_length=24)),
                ('payment_status', models.CharField(choices=[('not_required', 'Not Required / غير مطلوب'), ('pending', 'Pending / بانتظار الدفع'), ('submitted', 'Submitted / تم الإرسال'), ('confirmed', 'Confirmed / مؤكد'), ('rejected', 'Rejected / مرفوض')], db_index=True, default='not_required', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=150)),
                ('payment_receipt', models.FileField(blank=True, null=True, upload_to='subscriptions/onboarding/receipts/%Y/%m/')),
                ('admin_notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_journeys', to='directory.business')),
                ('selected_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merchant_onboardings', to='subscriptions.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_onboarding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Merchant Onboarding',
                'verbose_name_plural': 'Merchant Onboardings',
                'ordering': ['-updated_at'],
            },
        ),
    ]
