# Generated by Django 6.0.1 on 2026-01-29 17:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(help_text='رقم الهاتف المصري (01234567890)', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='أدخل رقم هاتف مصري صحيح (مثال: 01234567890)', regex='^01[0-2,5]{1}[0-9]{8}$')], verbose_name='Phone Number')),
                ('profile_picture', models.ImageField(blank=True, help_text='صورة شخصية (اختياري)', null=True, upload_to='profiles/%Y/%m/', verbose_name='Profile Picture')),
                ('bio', models.TextField(blank=True, help_text='نبذة عنك (اختياري)', max_length=500, verbose_name='Bio')),
                ('city', models.CharField(blank=True, help_text='المدينة', max_length=100, verbose_name='City')),
                ('email_verified', models.BooleanField(default=False, help_text='تم التحقق من البريد الإلكتروني', verbose_name='Email Verified')),
                ('is_business_owner', models.BooleanField(default=False, help_text='صاحب محل', verbose_name='Business Owner')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'), models.Index(fields=['phone'], name='accounts_us_phone_f54457_idx'), models.Index(fields=['is_business_owner'], name='accounts_us_is_busi_1e3a9d_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
