# Generated by Django 6.0.1 on 2026-01-29 17:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(db_index=True, help_text='Example: 50% Off on All Items', max_length=200, verbose_name='Title (English)')),
                ('title_ar', models.CharField(db_index=True, help_text='مثال: خصم 50% على جميع المنتجات', max_length=200, verbose_name='العنوان')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='URL Slug')),
                ('description_en', models.TextField(help_text='Full deal description in English', verbose_name='Description (English)')),
                ('description_ar', models.TextField(help_text='وصف كامل للعرض بالعربية', verbose_name='الوصف')),
                ('deal_type', models.CharField(choices=[('percentage', 'Percentage Discount / خصم بالنسبة'), ('fixed', 'Fixed Amount / قيمة ثابتة'), ('bogo', 'Buy One Get One / اشتري واحد واحصل على آخر'), ('bundle', 'Bundle Deal / عرض مجمع'), ('special', 'Special Offer / عرض خاص')], db_index=True, default='percentage', max_length=15, verbose_name='Deal Type')),
                ('discount_percentage', models.PositiveIntegerField(blank=True, help_text='For percentage discounts (e.g., 25 for 25%)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Discount Percentage')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='For fixed amount discounts', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount Amount (EGP)')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Original Price (EGP)')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Final Price (EGP)')),
                ('start_date', models.DateTimeField(help_text='When the deal becomes active', verbose_name='Start Date')),
                ('end_date', models.DateTimeField(help_text='When the deal expires', verbose_name='End Date')),
                ('terms_en', models.TextField(blank=True, help_text='Deal terms and conditions in English', verbose_name='Terms & Conditions (English)')),
                ('terms_ar', models.TextField(blank=True, help_text='شروط وأحكام العرض بالعربية', verbose_name='الشروط والأحكام')),
                ('image', models.ImageField(blank=True, help_text='Banner image for the deal (Recommended: 1200x600 px)', null=True, upload_to='deals/%Y/%m/', verbose_name='Deal Image')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Total number of times this deal can be claimed (Leave empty for unlimited)', null=True, verbose_name='Maximum Uses')),
                ('current_uses', models.PositiveIntegerField(default=0, editable=False, help_text='Number of times this deal has been claimed', verbose_name='Current Uses')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, help_text='How many times a single user can claim this deal', verbose_name='Max Uses Per User')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable deal visibility', verbose_name='Active')),
                ('is_featured', models.BooleanField(default=False, help_text='Display in featured deals section', verbose_name='Featured')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='View Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', related_query_name='deal', to='directory.business', verbose_name='Business')),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True, verbose_name='Claimed At')),
                ('is_used', models.BooleanField(default=False, help_text='Has the user actually used this deal?', verbose_name='Used')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Used At')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', related_query_name='claim', to='deals.deal', verbose_name='Deal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_claims', related_query_name='deal_claim', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Deal Claim',
                'verbose_name_plural': 'Deal Claims',
                'ordering': ['-claimed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['slug'], name='deals_deal_slug_6dc538_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['business', 'is_active'], name='deals_deal_busines_be9c55_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['deal_type'], name='deals_deal_deal_ty_0b9ede_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['start_date', 'end_date'], name='deals_deal_start_d_20cfdf_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['is_featured', '-created_at'], name='deals_deal_is_feat_da5013_idx'),
        ),
        migrations.AddIndex(
            model_name='dealclaim',
            index=models.Index(fields=['deal', 'user'], name='deals_dealc_deal_id_3768e0_idx'),
        ),
        migrations.AddIndex(
            model_name='dealclaim',
            index=models.Index(fields=['-claimed_at'], name='deals_dealc_claimed_8524b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dealclaim',
            unique_together={('deal', 'user', 'claimed_at')},
        ),
    ]
