# Generated by Django 6.0.1 on 2026-02-01 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dealclaim',
            unique_together=set(),
        ),
    ]
