# Generated by Django 6.0.1 on 2026-01-29 17:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(db_index=True, help_text='Product/Service name in English', max_length=200, verbose_name='Name (English)')),
                ('name_ar', models.CharField(db_index=True, help_text='اسم المنتج/الخدمة بالعربية', max_length=200, verbose_name='الاسم')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='URL Slug')),
                ('product_type', models.CharField(choices=[('product', 'Product / منتج'), ('service', 'Service / خدمة')], db_index=True, default='product', max_length=10, verbose_name='Type')),
                ('description_en', models.TextField(help_text='Detailed description in English', verbose_name='Description (English)')),
                ('description_ar', models.TextField(help_text='وصف تفصيلي بالعربية', verbose_name='الوصف')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in Egyptian Pounds', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price (EGP)')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='Previous price (for discount display)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Old Price (EGP)')),
                ('is_available', models.BooleanField(default=True, help_text='Is this product/service currently available?', verbose_name='Available')),
                ('stock_quantity', models.PositiveIntegerField(blank=True, help_text='Leave empty for unlimited stock', null=True, verbose_name='Stock Quantity')),
                ('has_delivery', models.BooleanField(default=False, verbose_name='Delivery Available')),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Delivery Cost (EGP)')),
                ('delivery_time_en', models.CharField(blank=True, help_text='Example: 1-2 business days', max_length=100, verbose_name='Delivery Time (English)')),
                ('delivery_time_ar', models.CharField(blank=True, help_text='مثال: 1-2 يوم عمل', max_length=100, verbose_name='وقت التوصيل')),
                ('order', models.IntegerField(default=0, help_text='Lower number = displayed first', verbose_name='Display Order')),
                ('is_featured', models.BooleanField(default=False, help_text='Display in featured products section', verbose_name='Featured')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Views')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', related_query_name='product', to='directory.business', verbose_name='Business')),
            ],
            options={
                'verbose_name': 'Product/Service',
                'verbose_name_plural': 'Products & Services',
                'ordering': ['business', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/%Y/%m/', verbose_name='Image')),
                ('alt_text_en', models.CharField(blank=True, help_text='Image description for SEO', max_length=200, verbose_name='Alt Text (English)')),
                ('alt_text_ar', models.CharField(blank=True, help_text='وصف الصورة لمحركات البحث', max_length=200, verbose_name='النص البديل')),
                ('is_primary', models.BooleanField(default=False, help_text='Main product image', verbose_name='Primary Image')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', related_query_name='image', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['-is_primary', 'order', '-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'is_available'], name='products_pr_busines_4426f7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type', 'is_available'], name='products_pr_product_8412e2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', '-created_at'], name='products_pr_is_feat_88faea_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-view_count'], name='products_pr_view_co_cba56c_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'is_primary'], name='products_pr_product_1b7905_idx'),
        ),
    ]
